package codegen

import (
	"fmt"
	"strings"
)

// RustTestCase describes one counterexample trace to turn into a #[test].
type RustTestCase struct {
	InvariantName string
	ActionPath    []string               // ordered action names leading to violation
	InitVars      map[string]interface{} // initial state variable values
	Steps         []RustTestStep
}

// RustTestStep is one transition in the counterexample.
type RustTestStep struct {
	Action   string
	Args     []interface{}
	Expected map[string]interface{} // expected state after this action
}

// EmitRustTests generates a Rust test file from a list of counterexample traces.
// specName is the spec file base name (used in comments).
// meta is the DriverMeta sidecar (may be nil; generates stub calls if absent).
func EmitRustTests(specName string, meta *DriverMeta, traces []RustTestCase) string {
	var b strings.Builder

	b.WriteString("// Auto-generated by spectre verify --emit-rust-tests\n")
	b.WriteString("// Regression tests for invariant violations found by the Spectre model checker.\n")
	b.WriteString("// Each test replays a counterexample trace against the real implementation.\n")
	b.WriteString("// Spec: " + specName + "\n\n")
	b.WriteString("#[cfg(test)]\n")
	b.WriteString("mod spectre_regressions {\n")
	b.WriteString("    use super::*;\n\n")

	for i, tc := range traces {
		fnName := testFnName(tc.InvariantName, tc.ActionPath)
		b.WriteString(fmt.Sprintf("    /// Counterexample %d: invariant `%s` violated via %s\n",
			i+1, tc.InvariantName, strings.Join(tc.ActionPath, " → ")))
		b.WriteString("    #[test]\n")
		b.WriteString(fmt.Sprintf("    fn %s() {\n", fnName))

		// Initial state comment
		if len(tc.InitVars) > 0 {
			b.WriteString("        // Initial state: ")
			parts := make([]string, 0, len(tc.InitVars))
			for k, v := range tc.InitVars {
				parts = append(parts, fmt.Sprintf("%s = %v", k, v))
			}
			b.WriteString(strings.Join(parts, ", ") + "\n")
		}

		// Derive struct name from meta or specName
		structName := specName
		if meta != nil {
			structName = meta.StructName
		}
		b.WriteString(fmt.Sprintf("        let mut obj = %s::new();\n", structName))

		for j, step := range tc.Steps {
			b.WriteString(fmt.Sprintf("        // step %d: %s\n", j+1, step.Action))
			methodName := step.Action
			if meta != nil {
				for _, ma := range meta.Actions {
					if ma.SpecAction == step.Action {
						methodName = ma.RustMethod
						break
					}
				}
			}
			argStrs := make([]string, len(step.Args))
			for k, a := range step.Args {
				argStrs[k] = fmt.Sprintf("%v", a)
			}
			b.WriteString(fmt.Sprintf("        obj.%s(%s);\n", methodName, strings.Join(argStrs, ", ")))
			if len(step.Expected) > 0 {
				b.WriteString("        // expected state after this step:\n")
				for k, v := range step.Expected {
					rustField := k
					if meta != nil {
						for _, mf := range meta.Fields {
							if mf.SpecVar == k {
								rustField = mf.RustField
								break
							}
						}
					}
					b.WriteString(fmt.Sprintf("        // %s = %v\n", rustField, v))
				}
			}
		}

		b.WriteString(fmt.Sprintf("        // If execution reaches here the implementation accepted a state\n"))
		b.WriteString(fmt.Sprintf("        // that the Spectre model says violates `%s`.\n", tc.InvariantName))
		b.WriteString("        // Add assertions here to make this a hard-failing test.\n")
		b.WriteString("    }\n\n")
	}

	b.WriteString("}\n")
	return b.String()
}

// testFnName builds a snake_case Rust test function name from invariant + action path.
func testFnName(invariant string, path []string) string {
	parts := []string{"ce", toSnake(invariant)}
	for _, a := range path {
		parts = append(parts, toSnake(a))
	}
	return strings.Join(parts, "_")
}

// toSnake converts a camelCase or PascalCase identifier to snake_case and
// strips characters that are invalid in Rust identifiers.
func toSnake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteRune('_')
			}
			b.WriteRune(r + 32)
		} else if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	// Collapse repeated underscores.
	result := b.String()
	for strings.Contains(result, "__") {
		result = strings.ReplaceAll(result, "__", "_")
	}
	return strings.Trim(result, "_")
}
