// Package codegen generates Rust driver skeletons for model-based testing
// via the spectre-connect crate.
package codegen

import (
	"fmt"
	"strings"

	"github.com/BoundlessProducts/spectre/pkg/ast"
)

// RustDriver holds everything extracted from a spec that is needed to generate
// a Rust driver skeleton.
type RustDriver struct {
	SpecName string
	Vars     []varInfo
	Actions  []actionInfo
	Enums    []enumInfo
}

type varInfo struct {
	Name    string
	ASTType ast.Type
}

type actionInfo struct {
	Name   string
	Params []paramInfo
}

type paramInfo struct {
	Name    string
	ASTType ast.Type
}

type enumInfo struct {
	Name   string
	Values []string
}

// ExtractFromAST walks an AST file and fills a RustDriver with the
// declarations relevant for driver generation.
func ExtractFromAST(file *ast.File, specName string) *RustDriver {
	d := &RustDriver{SpecName: specName}
	for _, decl := range file.Decls {
		d.collectDecl(decl)
	}
	return d
}

func (d *RustDriver) collectDecl(decl ast.Decl) {
	switch n := decl.(type) {
	case *ast.VariableDecl:
		d.Vars = append(d.Vars, varInfo{Name: n.Name, ASTType: n.Type})
	case *ast.ActionDecl:
		ai := actionInfo{Name: n.Name}
		for _, p := range n.Parameters {
			ai.Params = append(ai.Params, paramInfo{Name: p.Name, ASTType: p.Type})
		}
		d.Actions = append(d.Actions, ai)
	case *ast.EnumDecl:
		d.Enums = append(d.Enums, enumInfo{Name: n.Name, Values: n.Values})
	case *ast.ModuleDecl:
		for _, inner := range n.Decls {
			d.collectDecl(inner)
		}
	}
}

// Generate emits a complete Rust source file that the developer fills in to
// connect their implementation to Spectre traces via spectre-connect.
func (d *RustDriver) Generate() string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("// Auto-generated by `spectre generate-driver %s`\n", d.SpecName))
	b.WriteString("// Fill in the TODO sections to connect your Rust implementation.\n")
	b.WriteString("//\n")
	b.WriteString("// Add to your Cargo.toml:\n")
	b.WriteString("//   [dependencies]\n")
	b.WriteString("//   spectre-connect = \"0.1\"\n\n")

	b.WriteString("use spectre_connect::{ItfValue, StepHandler, TraceReplayer};\n")
	b.WriteString("use std::collections::HashMap;\n\n")

	// Emit enums
	for _, e := range d.Enums {
		b.WriteString(fmt.Sprintf("#[derive(Debug, Clone, PartialEq)]\n"))
		b.WriteString(fmt.Sprintf("pub enum %s {\n", e.Name))
		for _, v := range e.Values {
			b.WriteString(fmt.Sprintf("    %s,\n", v))
		}
		b.WriteString("}\n\n")

		// Emit From<String> so enum values can be decoded from ITF strings.
		b.WriteString(fmt.Sprintf("impl TryFrom<&str> for %s {\n", e.Name))
		b.WriteString("    type Error = String;\n")
		b.WriteString("    fn try_from(s: &str) -> Result<Self, Self::Error> {\n")
		b.WriteString("        match s {\n")
		for _, v := range e.Values {
			b.WriteString(fmt.Sprintf("            %q => Ok(%s::%s),\n", v, e.Name, v))
		}
		b.WriteString(fmt.Sprintf("            _ => Err(format!(\"unknown %s variant: {}\", s)),\n", e.Name))
		b.WriteString("        }\n")
		b.WriteString("    }\n}\n\n")
	}

	// State struct
	b.WriteString("/// Holds your system's state. Replace field types with your real types.\n")
	b.WriteString("pub struct MySystem {\n")
	for _, v := range d.Vars {
		rustType := rustTypeOf(v.ASTType)
		b.WriteString(fmt.Sprintf("    pub %s: %s, // TODO: adjust type\n", v.Name, rustType))
	}
	b.WriteString("}\n\n")

	// impl MySystem
	b.WriteString("impl MySystem {\n")
	b.WriteString("    pub fn new() -> Self {\n")
	b.WriteString("        Self {\n")
	for _, v := range d.Vars {
		b.WriteString(fmt.Sprintf("            %s: Default::default(), // TODO: set initial value\n", v.Name))
	}
	b.WriteString("        }\n")
	b.WriteString("    }\n}\n\n")

	// StepHandler impl
	b.WriteString("impl StepHandler for MySystem {\n")
	b.WriteString("    type Error = Box<dyn std::error::Error>;\n\n")

	// apply_action
	b.WriteString("    fn apply_action(&mut self, action: &str, args: &[ItfValue]) -> Result<(), Self::Error> {\n")
	b.WriteString("        match action {\n")
	for _, a := range d.Actions {
		b.WriteString(fmt.Sprintf("            %q => {\n", a.Name))
		for i, p := range a.Params {
			rustType := rustTypeOf(p.ASTType)
			b.WriteString(fmt.Sprintf("                let %s: %s = args.get(%d)\n", p.Name, rustType, i))
			b.WriteString(fmt.Sprintf("                    .ok_or(\"missing arg %d for %s\")?\n", i, a.Name))
			b.WriteString(fmt.Sprintf("                    .try_into()?;\n"))
		}
		b.WriteString("                // TODO: call your real implementation\n")
		b.WriteString("                todo!()\n")
		b.WriteString("            }\n")
	}
	b.WriteString("            _ => Err(format!(\"unknown action: {action}\").into()),\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n\n")

	// current_state
	b.WriteString("    fn current_state(&self) -> HashMap<String, ItfValue> {\n")
	b.WriteString("        let mut s = HashMap::new();\n")
	for _, v := range d.Vars {
		conv := itfConvOf(v.Name, v.ASTType)
		b.WriteString(fmt.Sprintf("        s.insert(%q.to_string(), %s);\n", v.Name, conv))
	}
	b.WriteString("        s\n")
	b.WriteString("    }\n}\n\n")

	// main
	b.WriteString("fn main() {\n")
	b.WriteString("    let trace_path = std::env::args().nth(1)\n")
	b.WriteString("        .unwrap_or_else(|| \"trace.itf.json\".to_string());\n\n")
	b.WriteString("    let system = MySystem::new();\n")
	b.WriteString("    let mut replayer = TraceReplayer::new(system);\n\n")
	b.WriteString("    let result = replayer.replay_file(&trace_path)\n")
	b.WriteString("        .expect(\"failed to replay trace\");\n\n")
	b.WriteString("    if result.mismatches.is_empty() {\n")
	b.WriteString("        println!(\"✓ All {} steps matched the spec\", result.steps_executed);\n")
	b.WriteString("    } else {\n")
	b.WriteString("        eprintln!(\"✗ {} mismatch(es):\", result.mismatches.len());\n")
	b.WriteString("        for m in &result.mismatches {\n")
	b.WriteString("            eprintln!(\"  step {}, action '{}', var '{}': expected {:?}, got {:?}\",\n")
	b.WriteString("                m.step, m.action, m.variable, m.expected, m.actual);\n")
	b.WriteString("        }\n")
	b.WriteString("        std::process::exit(1);\n")
	b.WriteString("    }\n}\n")

	return b.String()
}

// GenerateWithMeta emits a fully-connected Rust adapter using the field/method
// mapping recorded in the mining sidecar.  Spec variables or actions that are
// absent from the sidecar (added or renamed after mining) receive annotated
// todo!() stubs so the user knows exactly what to fill in.
func (d *RustDriver) GenerateWithMeta(meta *DriverMeta) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("// Auto-generated by `spectre generate-driver %s`\n", d.SpecName))
	b.WriteString(fmt.Sprintf("// Source mapping: %s (%s)\n", meta.SourceFile, meta.StructName))
	b.WriteString("//\n")
	b.WriteString("// apply_action() and current_state() are fully generated from the mining\n")
	b.WriteString("// sidecar — no manual edits required for primitive-typed fields.\n")
	b.WriteString("//\n")
	b.WriteString("// Drift: if you renamed spec variables or actions after mining, regenerate\n")
	b.WriteString("// with: spectre mine -o <spec> <source.rs> && spectre generate-driver <spec>\n\n")

	b.WriteString("use spectre_connect::{ItfValue, StepHandler, TraceReplayer};\n")
	b.WriteString("use std::collections::HashMap;\n\n")

	// Emit enums (with TryFrom<&str> for ITF decoding)
	for _, e := range d.Enums {
		b.WriteString("#[derive(Debug, Clone, PartialEq)]\n")
		b.WriteString(fmt.Sprintf("pub enum %s {\n", e.Name))
		for _, v := range e.Values {
			b.WriteString(fmt.Sprintf("    %s,\n", v))
		}
		b.WriteString("}\n\n")
		b.WriteString(fmt.Sprintf("impl TryFrom<&str> for %s {\n", e.Name))
		b.WriteString("    type Error = String;\n")
		b.WriteString("    fn try_from(s: &str) -> Result<Self, Self::Error> {\n")
		b.WriteString("        match s {\n")
		for _, v := range e.Values {
			b.WriteString(fmt.Sprintf("            %q => Ok(%s::%s),\n", v, e.Name, v))
		}
		b.WriteString(fmt.Sprintf("            _ => Err(format!(\"unknown %s variant: {}\", s)),\n", e.Name))
		b.WriteString("        }\n    }\n}\n\n")
	}

	// Build lookup maps from the sidecar
	fieldBySpecVar := make(map[string]*MetaField)
	for i := range meta.Fields {
		fieldBySpecVar[meta.Fields[i].SpecVar] = &meta.Fields[i]
	}
	actionBySpecName := make(map[string]*MetaAction)
	for i := range meta.Actions {
		actionBySpecName[meta.Actions[i].SpecAction] = &meta.Actions[i]
	}

	// Detect drift: spec elements not present in the sidecar
	var driftVars, driftActions []string
	for _, v := range d.Vars {
		if _, ok := fieldBySpecVar[v.Name]; !ok {
			driftVars = append(driftVars, v.Name)
		}
	}
	for _, a := range d.Actions {
		if _, ok := actionBySpecName[a.Name]; !ok {
			driftActions = append(driftActions, a.Name)
		}
	}
	if len(driftVars)+len(driftActions) > 0 {
		b.WriteString("// NOTE: the following spec elements have no Rust source mapping\n")
		b.WriteString("// (added or renamed after mining). Fill in the stubs marked TODO below.\n")
		for _, v := range driftVars {
			b.WriteString(fmt.Sprintf("//   variable: %s\n", v))
		}
		for _, a := range driftActions {
			b.WriteString(fmt.Sprintf("//   action:   %s\n", a))
		}
		b.WriteString("\n")
	}

	// Import hint
	b.WriteString(fmt.Sprintf("// TODO: add the correct `use` path for %s, e.g.:\n", meta.StructName))
	b.WriteString(fmt.Sprintf("// use your_crate::%s;\n\n", meta.StructName))

	// impl StepHandler for the real struct
	b.WriteString(fmt.Sprintf("impl StepHandler for %s {\n", meta.StructName))
	b.WriteString("    type Error = Box<dyn std::error::Error>;\n\n")

	// apply_action
	b.WriteString("    fn apply_action(&mut self, action: &str, args: &[ItfValue]) -> Result<(), Self::Error> {\n")
	b.WriteString("        match action {\n")
	for _, a := range d.Actions {
		if ma, ok := actionBySpecName[a.Name]; ok {
			b.WriteString(fmt.Sprintf("            %q => {\n", a.Name))
			paramNames := make([]string, len(ma.Params))
			for i, p := range ma.Params {
				rt := p.RustType
				if rt == "" {
					rt = spectreTypeToRust(p.SpectreType)
				}
				extract := metaExtractExpr(i, a.Name, rt)
				b.WriteString(fmt.Sprintf("                let %s: %s = %s;\n", p.Name, rt, extract))
				paramNames[i] = p.Name
			}
			if len(paramNames) == 0 {
				b.WriteString(fmt.Sprintf("                self.%s();\n", ma.RustMethod))
			} else {
				b.WriteString(fmt.Sprintf("                self.%s(%s);\n", ma.RustMethod, strings.Join(paramNames, ", ")))
			}
			b.WriteString("                Ok(())\n")
			b.WriteString("            }\n")
		} else {
			b.WriteString(fmt.Sprintf("            %q => {\n", a.Name))
			b.WriteString(fmt.Sprintf("                // TODO: no Rust method for action %q (added after mining)\n", a.Name))
			b.WriteString("                todo!()\n")
			b.WriteString("            }\n")
		}
	}
	b.WriteString("            _ => Err(format!(\"unknown action: {action}\").into()),\n")
	b.WriteString("        }\n    }\n\n")

	// current_state
	b.WriteString("    fn current_state(&self) -> HashMap<String, ItfValue> {\n")
	b.WriteString("        let mut s = HashMap::new();\n")
	for _, v := range d.Vars {
		if mf, ok := fieldBySpecVar[v.Name]; ok {
			conv := metaItfConv(mf.RustField, mf.RustType)
			b.WriteString(fmt.Sprintf("        s.insert(%q.to_string(), %s);\n", v.Name, conv))
		} else {
			b.WriteString(fmt.Sprintf("        // TODO: map spec variable %q to your implementation\n", v.Name))
			b.WriteString(fmt.Sprintf("        // s.insert(%q.to_string(), ...);\n", v.Name))
		}
	}
	b.WriteString("        s\n    }\n}\n\n")

	// main
	b.WriteString("fn main() {\n")
	b.WriteString("    let trace_path = std::env::args().nth(1)\n")
	b.WriteString("        .unwrap_or_else(|| \"trace.itf.json\".to_string());\n\n")
	b.WriteString(fmt.Sprintf("    // TODO: initialize %s with the correct arguments\n", meta.StructName))
	b.WriteString(fmt.Sprintf("    let system = %s::new();\n", meta.StructName))
	b.WriteString("    let mut replayer = TraceReplayer::new(system);\n")
	b.WriteString("    let result = replayer.replay_file(&trace_path)\n")
	b.WriteString("        .expect(\"failed to replay trace\");\n\n")
	b.WriteString("    if result.mismatches.is_empty() {\n")
	b.WriteString("        println!(\"✓ All {} steps matched the spec\", result.steps_executed);\n")
	b.WriteString("    } else {\n")
	b.WriteString("        eprintln!(\"✗ {} mismatch(es):\", result.mismatches.len());\n")
	b.WriteString("        for m in &result.mismatches {\n")
	b.WriteString("            eprintln!(\"  step {}, action '{}', var '{}': expected {:?}, got {:?}\",\n")
	b.WriteString("                m.step, m.action, m.variable, m.expected, m.actual);\n")
	b.WriteString("        }\n")
	b.WriteString("        std::process::exit(1);\n")
	b.WriteString("    }\n}\n")

	return b.String()
}

// metaExtractExpr generates the Rust expression to pull argument i from args.
func metaExtractExpr(i int, actionName, rustType string) string {
	base := fmt.Sprintf("args.get(%d).ok_or(\"missing arg %d for %s\")?.try_into()?", i, i, actionName)
	switch rustType {
	case "i8", "i16", "i32", "u8", "u16", "u32", "u64", "u128", "usize", "isize":
		return fmt.Sprintf("{ let _v: i64 = args.get(%d).ok_or(\"missing arg %d for %s\")?.try_into()?; _v as %s }",
			i, i, actionName, rustType)
	}
	return base
}

// metaItfConv generates a Rust expression that converts self.fieldName to ItfValue.
func metaItfConv(fieldName, rustType string) string {
	switch rustType {
	case "i64":
		return fmt.Sprintf("ItfValue::Int(self.%s)", fieldName)
	case "i8", "i16", "i32", "i128", "u8", "u16", "u32", "u64", "u128", "usize", "isize":
		return fmt.Sprintf("ItfValue::Int(self.%s as i64)", fieldName)
	case "bool":
		return fmt.Sprintf("ItfValue::Bool(self.%s)", fieldName)
	case "String":
		return fmt.Sprintf("ItfValue::Str(self.%s.clone())", fieldName)
	case "str", "&str":
		return fmt.Sprintf("ItfValue::Str(self.%s.to_string())", fieldName)
	case "f32", "f64":
		return fmt.Sprintf("ItfValue::Float(self.%s as f64)", fieldName)
	default:
		// enum or unknown — format via Debug
		return fmt.Sprintf("ItfValue::Str(format!(\"{:?}\", self.%s))", fieldName)
	}
}

// rustTypeOf maps a Spectre AST type to an approximate Rust type string.
func rustTypeOf(t ast.Type) string {
	if t == nil {
		return "ItfValue"
	}
	switch typ := t.(type) {
	case *ast.PrimitiveType:
		switch typ.Name {
		case "int":
			return "i64"
		case "bool":
			return "bool"
		case "str":
			return "String"
		case "float":
			return "f64"
		}
	case *ast.SetType:
		return fmt.Sprintf("std::collections::HashSet<%s>", rustTypeOf(typ.Element))
	case *ast.ListType:
		return fmt.Sprintf("Vec<%s>", rustTypeOf(typ.Element))
	case *ast.MapType:
		return fmt.Sprintf("std::collections::HashMap<%s, %s>", rustTypeOf(typ.Key), rustTypeOf(typ.Value))
	case *ast.OptionType:
		return fmt.Sprintf("Option<%s>", rustTypeOf(typ.Element))
	case *ast.NamedType:
		return typ.Name // e.g. enum name
	case *ast.RecordType:
		return "HashMap<String, ItfValue>"
	}
	return "ItfValue"
}

// itfConvOf generates a Rust expression that converts self.varName to ItfValue.
func itfConvOf(varName string, t ast.Type) string {
	if t == nil {
		return fmt.Sprintf("self.%s.clone()", varName)
	}
	switch typ := t.(type) {
	case *ast.PrimitiveType:
		switch typ.Name {
		case "int":
			return fmt.Sprintf("ItfValue::Int(self.%s)", varName)
		case "bool":
			return fmt.Sprintf("ItfValue::Bool(self.%s)", varName)
		case "str":
			return fmt.Sprintf("ItfValue::Str(self.%s.clone())", varName)
		case "float":
			return fmt.Sprintf("ItfValue::Float(self.%s)", varName)
		}
	case *ast.NamedType:
		// Enum: convert variant name to ItfValue::Str
		return fmt.Sprintf("ItfValue::Str(format!(\"{:?}\", self.%s))", varName)
	}
	return fmt.Sprintf("ItfValue::Str(format!(\"{:?}\", self.%s))", varName)
}
