package codegen

import (
	"fmt"
	"strings"

	"github.com/akkeshavan/spectre/pkg/ast"
)

// EmitProptestModule generates a Rust module containing proptest strategies
// derived from a Spectre spec's invariants and action guards.
//
// Each invariant clause becomes a precondition filter on the strategy;
// each action's guard becomes an `assume!` in the property test body.
// The generated file requires proptest ≥ 1.0 in Cargo.toml.
func EmitProptestModule(specName string, file *ast.File, meta *DriverMeta) string {
	var b strings.Builder

	b.WriteString("// Auto-generated by spectre verify --emit-proptest\n")
	b.WriteString("// Parameterised property tests derived from the Spectre spec: " + specName + "\n")
	b.WriteString("// Requires: proptest = \"1\" in [dev-dependencies]\n\n")
	b.WriteString("#[cfg(test)]\n")
	b.WriteString("mod spectre_proptest {\n")
	b.WriteString("    use super::*;\n")
	b.WriteString("    use proptest::prelude::*;\n\n")

	// Generate one proptest for each action that has guards.
	for _, d := range file.Decls {
		a, ok := d.(*ast.ActionDecl)
		if !ok || a.Body == nil {
			continue
		}

		guards := collectGuards(a)
		assigns := collectAssignNames(a)
		if len(guards) == 0 && len(assigns) == 0 {
			continue
		}

		// Find the corresponding Rust method name.
		rustMethod := a.Name
		if meta != nil {
			for _, ma := range meta.Actions {
				if ma.SpecAction == a.Name {
					rustMethod = ma.RustMethod
					break
				}
			}
		}

		// Build strategy for action parameters.
		params := actionParamStrategies(a, meta)

		b.WriteString(fmt.Sprintf("    proptest! {\n"))
		b.WriteString(fmt.Sprintf("        /// Property test for action `%s`\n", a.Name))
		b.WriteString(fmt.Sprintf("        #[test]\n"))
		b.WriteString(fmt.Sprintf("        fn prop_%s(%s) {\n", toSnake(a.Name), params))

		// Assume guards hold (pre-conditions).
		for _, g := range guards {
			b.WriteString(fmt.Sprintf("            prop_assume!(%s);\n", guardToRust(g, meta)))
		}

		b.WriteString(fmt.Sprintf("            let mut obj = /* TODO: construct initial state */;\n"))
		b.WriteString(fmt.Sprintf("            // Call the implementation method and assert post-conditions:\n"))
		b.WriteString(fmt.Sprintf("            let _ = obj.%s(/* args */);\n", rustMethod))

		// Assert invariants that reference variables written by this action.
		invs := collectInvariantsForAction(file, assigns)
		for _, inv := range invs {
			rustCond := guardToRust(inv.Condition, meta)
			b.WriteString(fmt.Sprintf("            prop_assert!(%s, \"invariant %s\");\n", rustCond, inv.Name))
		}
		b.WriteString("        }\n    }\n\n")
	}

	b.WriteString("}\n")
	return b.String()
}

func collectGuards(a *ast.ActionDecl) []ast.Expr {
	var guards []ast.Expr
	for _, s := range a.Body.Statements {
		if req, ok := s.(*ast.RequireStmt); ok {
			guards = append(guards, req.Condition)
		}
	}
	return guards
}

func collectAssignNames(a *ast.ActionDecl) map[string]bool {
	written := make(map[string]bool)
	for _, s := range a.Body.Statements {
		if assign, ok := s.(*ast.AssignStmt); ok {
			if id, ok := assign.Left.(*ast.Ident); ok {
				written[id.Name] = true
			}
		}
	}
	return written
}

// actionParamStrategies generates proptest strategy expressions for action parameters.
func actionParamStrategies(a *ast.ActionDecl, meta *DriverMeta) string {
	if len(a.Parameters) == 0 {
		return ""
	}
	parts := make([]string, 0, len(a.Parameters))
	for _, p := range a.Parameters {
		strategy := paramStrategy(p.Type, meta)
		parts = append(parts, fmt.Sprintf("%s in %s", p.Name, strategy))
	}
	return strings.Join(parts, ", ")
}

// paramStrategy returns a proptest strategy expression for a Spectre type.
func paramStrategy(t ast.Type, _ *DriverMeta) string {
	if t == nil {
		return "any::<i64>()"
	}
	switch typ := t.(type) {
	case *ast.PrimitiveType:
		switch typ.Name {
		case "int":
			return "any::<i64>()"
		case "bool":
			return "any::<bool>()"
		case "str":
			return `".*"`
		}
	}
	return "any::<i64>()"
}

// guardToRust converts a guard AST expression to a Rust prop_assume! argument (best-effort).
func guardToRust(e ast.Expr, meta *DriverMeta) string {
	var fm map[string]string
	if meta != nil {
		fm = make(map[string]string)
		for _, f := range meta.Fields {
			fm[f.SpecVar] = "obj." + f.RustField
		}
	}
	r, err := exprToRust(e, fm)
	if err != nil {
		return "true /* TODO: translate " + printExprSimple(e) + " */"
	}
	return r
}

// collectInvariantsForAction finds invariants that reference variables written by this action.
func collectInvariantsForAction(file *ast.File, written map[string]bool) []*ast.InvariantDecl {
	var invs []*ast.InvariantDecl
	for _, d := range file.Decls {
		if inv, ok := d.(*ast.InvariantDecl); ok {
			if exprRefsAny(inv.Condition, written) {
				invs = append(invs, inv)
			}
		}
	}
	return invs
}

func exprRefsAny(e ast.Expr, vars map[string]bool) bool {
	switch expr := e.(type) {
	case *ast.Ident:
		return vars[expr.Name]
	case *ast.BinaryExpr:
		return exprRefsAny(expr.Left, vars) || exprRefsAny(expr.Right, vars)
	case *ast.UnaryExpr:
		return exprRefsAny(expr.Expr, vars)
	case *ast.ParenExpr:
		return exprRefsAny(expr.X, vars)
	case *ast.IndexExpr:
		return exprRefsAny(expr.X, vars) || exprRefsAny(expr.Index, vars)
	}
	return false
}

func printExprSimple(e ast.Expr) string {
	switch expr := e.(type) {
	case *ast.Ident:
		return expr.Name
	case *ast.BasicLit:
		return expr.Value
	case *ast.BinaryExpr:
		return printExprSimple(expr.Left) + " op " + printExprSimple(expr.Right)
	}
	return "..."
}
