// Spectre spec mined from: examples/rust/counter.rs
// Generated by: spectre mine --lang rust
// Review and refine before use in verification.

// ── State ──────────────────────────────────────────────
// Mined from: struct Counter

var count: int
var step: int
var max: int

init {
  count = 0
  step = 0
  max = 0
}

// ── Actions ────────────────────────────────────────────
// Mined from: impl Counter

description "Mined from: func increment"
action increment {
  require count + step <= max
  count' = count + step
}

description "Mined from: func decrement"
action decrement {
  require count >= step
  count' = count - step
}

description "Mined from: func reset"
action reset {
  count' = 0
}

// ── Temporal properties ────────────────────────────────
// Uncomment and refine the properties that apply to your system.

// Weak fairness: ensures reset makes progress when enabled
// temporal progress_reset {
//   WF(reset)
// }

