package mine

import (
	"fmt"
	"strings"
)

// LLMSuggestions holds optional enhancements from an LLM analysis pass.
// All fields are optional; the generator uses static analysis when they are nil/empty.
type LLMSuggestions struct {
	// ActionNotes maps method name → a natural-language note to embed as a comment.
	ActionNotes map[string]string
	// ExtraInvariants are additional invariant conditions suggested by the LLM.
	ExtraInvariants []LLMInvariant
	// ExtraTemporal are temporal property suggestions from the LLM.
	ExtraTemporal []LLMTemporal
	// Raw is the full LLM response text (for debugging / transparency).
	Raw string
}

// LLMInvariant is one LLM-suggested invariant.
type LLMInvariant struct {
	Name        string
	Condition   string // Spectre expression
	Description string
}

// LLMTemporal is one LLM-suggested temporal property.
type LLMTemporal struct {
	Name        string
	Expression  string // Spectre temporal expression
	Description string
}

// Generate produces a Spectre spec skeleton from the mined data and optional
// LLM suggestions.  The result is valid Spectre source that can be written
// to a .spec file and refined by hand.
func (m *MinedSpec) Generate(s *LLMSuggestions) string {
	if s == nil {
		s = &LLMSuggestions{}
	}
	var b strings.Builder

	// ── header ────────────────────────────────────────────────────────────────
	b.WriteString(fmt.Sprintf("// Spectre spec mined from: %s\n", m.SourceFile))
	b.WriteString("// Generated by: spectre mine --lang rust\n")
	b.WriteString("// Review and refine before use in verification.\n\n")

	// ── enums ─────────────────────────────────────────────────────────────────
	for _, e := range m.Enums {
		b.WriteString(fmt.Sprintf("enum %s {\n", e.Name))
		for i, v := range e.Variants {
			if i < len(e.Variants)-1 {
				b.WriteString(fmt.Sprintf("  %s,\n", v))
			} else {
				b.WriteString(fmt.Sprintf("  %s\n", v))
			}
		}
		b.WriteString("}\n\n")
	}

	// ── state variables ───────────────────────────────────────────────────────
	b.WriteString("// ── State ──────────────────────────────────────────────\n")
	if m.StructName != "" {
		b.WriteString(fmt.Sprintf("// Mined from: struct %s\n\n", m.StructName))
	}

	for _, f := range m.Fields {
		spectreType := f.SpectreType
		b.WriteString(fmt.Sprintf("var %s: %s\n", f.Name, spectreType))
	}
	b.WriteString("\n")

	// ── init block ────────────────────────────────────────────────────────────
	b.WriteString("init {\n")
	for _, f := range m.Fields {
		def := f.Default
		// Fix enum defaults: use first known variant instead of "Enum.Default".
		if strings.Contains(def, ".Default") {
			typeName := strings.TrimSuffix(def, ".Default")
			if better := enumDefaultValue(typeName, m.Enums); better != "" {
				def = better
			}
		}
		b.WriteString(fmt.Sprintf("  %s = %s\n", f.Name, def))
	}
	b.WriteString("}\n\n")

	// ── actions ───────────────────────────────────────────────────────────────
	b.WriteString("// ── Actions ────────────────────────────────────────────\n")
	if m.StructName != "" {
		b.WriteString(fmt.Sprintf("// Mined from: impl %s\n\n", m.StructName))
	}

	for _, meth := range m.Methods {
		writeAction(&b, meth, s, m)
	}

	// ── invariants ────────────────────────────────────────────────────────────
	staticInvs := deriveInvariants(m)
	if len(staticInvs) > 0 || len(s.ExtraInvariants) > 0 {
		b.WriteString("// ── Invariants ─────────────────────────────────────────\n")
		b.WriteString("// Synthesized from assert patterns found in the Rust source.\n\n")
		for _, inv := range staticInvs {
			b.WriteString(fmt.Sprintf("description %q\n", inv.Description))
			b.WriteString(fmt.Sprintf("invariant %s {\n", inv.Name))
			b.WriteString(fmt.Sprintf("  %s\n", inv.Condition))
			b.WriteString("}\n\n")
		}
		for _, inv := range s.ExtraInvariants {
			b.WriteString(fmt.Sprintf("// LLM suggestion:\n"))
			b.WriteString(fmt.Sprintf("description %q\n", inv.Description))
			b.WriteString(fmt.Sprintf("invariant %s {\n", inv.Name))
			b.WriteString(fmt.Sprintf("  %s\n", inv.Condition))
			b.WriteString("}\n\n")
		}
	}

	// ── temporal ──────────────────────────────────────────────────────────────
	staticTemp := deriveTemporalProps(m)
	allTemp := append(staticTemp, s.ExtraTemporal...)
	if len(allTemp) > 0 {
		b.WriteString("// ── Temporal properties ────────────────────────────────\n")
		b.WriteString("// Uncomment and refine the properties that apply to your system.\n\n")
		for _, tp := range allTemp {
			b.WriteString(fmt.Sprintf("// %s\n", tp.Description))
			b.WriteString("// temporal " + tp.Name + " {\n")
			b.WriteString("//   " + tp.Expression + "\n")
			b.WriteString("// }\n\n")
		}
	}

	// ── LLM notes ─────────────────────────────────────────────────────────────
	if s.Raw != "" {
		b.WriteString("// ── LLM analysis notes ─────────────────────────────────\n")
		b.WriteString("// Full LLM response:\n")
		for _, line := range strings.Split(s.Raw, "\n") {
			b.WriteString("// " + line + "\n")
		}
	}

	return b.String()
}

// writeAction writes one action block to the builder.
func writeAction(b *strings.Builder, meth RustMethod, s *LLMSuggestions, m *MinedSpec) {
	// Description from LLM note or a default.
	desc := fmt.Sprintf("Mined from: func %s", meth.Name)
	if note, ok := s.ActionNotes[meth.Name]; ok {
		desc = note
	}
	b.WriteString(fmt.Sprintf("description %q\n", desc))

	// Action signature.
	if len(meth.Params) > 0 {
		paramStrs := make([]string, len(meth.Params))
		for i, p := range meth.Params {
			paramStrs[i] = p.Name + ": " + p.SpectreType
		}
		b.WriteString(fmt.Sprintf("action %s(%s) {\n", meth.Name, strings.Join(paramStrs, ", ")))
	} else {
		b.WriteString(fmt.Sprintf("action %s {\n", meth.Name))
	}

	// Require guards.
	for _, req := range meth.Requires {
		b.WriteString(fmt.Sprintf("  require %s\n", req))
	}

	// Assignments.
	for _, asgn := range meth.Assigns {
		rhs := rustAssignToSpectre(asgn.Field, asgn.Op, asgn.RHSRust)
		b.WriteString(fmt.Sprintf("  %s' = %s\n", asgn.Field, rhs))
	}

	// If no assignments were detected, add a placeholder.
	if len(meth.Assigns) == 0 && meth.MutSelf {
		b.WriteString("  // TODO: add state assignments (e.g. field' = newValue)\n")
	}

	b.WriteString("}\n\n")
}

// deriveInvariants synthesizes invariant candidates from assert patterns that
// appear in 2+ distinct methods and contain a comparison operator (so we only
// produce universally-plausible safety properties, not state-specific guards).
func deriveInvariants(m *MinedSpec) []LLMInvariant {
	fieldNames := fieldNameSet(m.Fields)

	// condCount tracks how many distinct methods each condition appears in.
	condCount := make(map[string]int)
	condDesc := make(map[string]string)

	for _, meth := range m.Methods {
		methParams := make(map[string]bool)
		for _, p := range meth.Params {
			methParams[p.Name] = true
		}
		seen := make(map[string]bool)
		for _, req := range meth.Requires {
			// Must reference a state field, no method params, and contain a comparison.
			if containsAnyToken(req, methParams) {
				continue
			}
			if !containsAnyToken(req, fieldNames) {
				continue
			}
			if !containsComparisonOp(req) {
				continue
			}
			if !seen[req] {
				seen[req] = true
				condCount[req]++
				if condDesc[req] == "" {
					condDesc[req] = fmt.Sprintf("Mined from: assert pattern in %s", meth.Name)
				}
			}
		}
	}

	var invs []LLMInvariant
	i := 0
	for cond, count := range condCount {
		if count < 2 {
			continue // only conditions shared across multiple methods are invariant candidates
		}
		name := fmt.Sprintf("mined_invariant_%d", i+1)
		invs = append(invs, LLMInvariant{
			Name:        name,
			Condition:   cond,
			Description: condDesc[cond],
		})
		i++
	}
	return invs
}

// containsComparisonOp reports whether s contains a relational operator,
// indicating it's a non-trivial condition (not just a boolean field check).
func containsComparisonOp(s string) bool {
	for _, op := range []string{">=", "<=", ">", "<", " = ", "!="} {
		if strings.Contains(s, op) {
			return true
		}
	}
	return false
}

// deriveTemporalProps suggests temporal properties based on structural patterns:
//   - Paired actions (e.g. open/close, lock/unlock) → WF suggestions
//   - Enum state machines → eventually properties
func deriveTemporalProps(m *MinedSpec) []LLMTemporal {
	var temps []LLMTemporal

	// Pattern 1: paired action names (open/close, lock/unlock, start/stop, etc.)
	pairs := [][2]string{
		{"start", "stop"}, {"open", "close"}, {"lock", "unlock"},
		{"acquire", "release"}, {"begin", "end"}, {"connect", "disconnect"},
		{"enqueue", "dequeue"}, {"push", "pop"}, {"send", "receive"},
		{"enable", "disable"}, {"activate", "deactivate"},
	}
	methodNames := make(map[string]bool)
	for _, meth := range m.Methods {
		methodNames[meth.Name] = true
	}
	for _, pair := range pairs {
		a, b := pair[0], pair[1]
		if methodContaining(methodNames, a) && methodContaining(methodNames, b) {
			aName := findMethod(methodNames, a)
			bName := findMethod(methodNames, b)
			temps = append(temps, LLMTemporal{
				Name:        "progress_" + aName,
				Expression:  "WF(" + aName + ")",
				Description: fmt.Sprintf("Weak fairness: %s is eventually taken when continuously enabled", aName),
			})
			temps = append(temps, LLMTemporal{
				Name:        "progress_" + bName,
				Expression:  "WF(" + bName + ")",
				Description: fmt.Sprintf("Weak fairness: %s is eventually taken when continuously enabled", bName),
			})
		}
	}

	// Pattern 2: enum state variables → suggest eventually reaches each variant.
	for _, f := range m.Fields {
		for _, e := range m.Enums {
			if f.SpectreType == e.Name && len(e.Variants) > 1 {
				// Suggest "eventually reaches terminal state".
				last := e.Variants[len(e.Variants)-1]
				propName := "eventually_" + camelToSnake(f.Name) + "_" + camelToSnake(last)
				temps = append(temps, LLMTemporal{
					Name:        propName,
					Expression:  fmt.Sprintf("eventually (%s = %s.%s)", f.Name, e.Name, last),
					Description: fmt.Sprintf("Liveness: %s field eventually reaches %s.%s", f.Name, e.Name, last),
				})
				break
			}
		}
	}

	// Pattern 3: for each mutable action that has no matching guard for a
	// field, suggest WF fairness.
	for _, meth := range m.Methods {
		if meth.MutSelf && len(meth.Assigns) > 0 && len(meth.Requires) == 0 {
			temps = append(temps, LLMTemporal{
				Name:        "progress_" + meth.Name,
				Expression:  "WF(" + meth.Name + ")",
				Description: fmt.Sprintf("Weak fairness: ensures %s makes progress when enabled", meth.Name),
			})
		}
	}

	// Deduplicate by Name.
	seen := make(map[string]bool)
	var deduped []LLMTemporal
	for _, t := range temps {
		if !seen[t.Name] {
			seen[t.Name] = true
			deduped = append(deduped, t)
		}
	}
	return deduped
}

// InvariantCandidate is a proposed invariant awaiting user approval.
type InvariantCandidate struct {
	Name        string
	Condition   string // Spectre expression
	Description string
	Source      string // "assert", "type-bound", "field-relation", "recurring-guard"
	Confidence  string // "high" | "medium" | "low"
}

// ProposeInvariantCandidates mines invariant candidates from the mined spec
// across five sources, returning candidates for user approval.  The caller
// must obtain explicit user confirmation before adding any candidate to the
// live spec (to avoid circular oracle issues).
//
// Sources:
//  1. Recurring guard conditions (2+ methods) — already in deriveInvariants
//  2. Single-method assertions that reference only field names (high confidence)
//  3. Integer field type-bounds (e.g., uint8 → 0 <= x && x <= 255)
//  4. Constructor postconditions (conditions in new() / default() methods)
//  5. Structural field relationships inferred from naming (len/capacity, used/size)
func ProposeInvariantCandidates(m *MinedSpec) []InvariantCandidate {
	fieldNames := fieldNameSet(m.Fields)
	var candidates []InvariantCandidate
	seen := make(map[string]bool)

	add := func(c InvariantCandidate) {
		if !seen[c.Condition] {
			seen[c.Condition] = true
			candidates = append(candidates, c)
		}
	}

	// Source 1: recurring guards (2+ methods) — high confidence.
	condCount := make(map[string]int)
	condDesc := make(map[string]string)
	condSource := make(map[string]string)
	for _, meth := range m.Methods {
		methParams := make(map[string]bool)
		for _, p := range meth.Params {
			methParams[p.Name] = true
		}
		seen2 := make(map[string]bool)
		for _, req := range meth.Requires {
			if containsAnyToken(req, methParams) {
				continue
			}
			if !containsAnyToken(req, fieldNames) {
				continue
			}
			if !containsComparisonOp(req) {
				continue
			}
			if !seen2[req] {
				seen2[req] = true
				condCount[req]++
				if condDesc[req] == "" {
					condDesc[req] = "recurring guard in " + meth.Name
					condSource[req] = "recurring-guard"
				}
			}
		}
	}
	idx := 1
	for cond, count := range condCount {
		conf := "medium"
		if count >= 2 {
			conf = "high"
		}
		add(InvariantCandidate{
			Name:        fmt.Sprintf("candidate_%d", idx),
			Condition:   cond,
			Description: condDesc[cond],
			Source:      condSource[cond],
			Confidence:  conf,
		})
		idx++
	}

	// Source 2: single-method assertions that reference only field names.
	for _, meth := range m.Methods {
		methParams := make(map[string]bool)
		for _, p := range meth.Params {
			methParams[p.Name] = true
		}
		for _, req := range meth.Requires {
			if containsAnyToken(req, methParams) {
				continue
			}
			if !containsAnyToken(req, fieldNames) {
				continue
			}
			if !containsComparisonOp(req) {
				continue
			}
			add(InvariantCandidate{
				Name:        fmt.Sprintf("candidate_%d", idx),
				Condition:   req,
				Description: "assert condition in " + meth.Name,
				Source:      "assert",
				Confidence:  "medium",
			})
			idx++
		}
	}

	// Source 3: integer type bounds.
	for _, f := range m.Fields {
		cond := typeBoundCondition(f.Name, f.RustType)
		if cond != "" {
			add(InvariantCandidate{
				Name:        fmt.Sprintf("candidate_%d", idx),
				Condition:   cond,
				Description: "type bound for field " + f.Name + " (" + f.RustType + ")",
				Source:      "type-bound",
				Confidence:  "high",
			})
			idx++
		}
	}

	// Source 4: constructor postconditions (new/default/init methods with no mut self).
	for _, meth := range m.Methods {
		name := strings.ToLower(meth.Name)
		if name != "new" && name != "default" && !strings.HasPrefix(name, "init") {
			continue
		}
		for _, req := range meth.Requires {
			if !containsAnyToken(req, fieldNames) {
				continue
			}
			add(InvariantCandidate{
				Name:        fmt.Sprintf("candidate_%d", idx),
				Condition:   req,
				Description: "constructor postcondition in " + meth.Name,
				Source:      "assert",
				Confidence:  "medium",
			})
			idx++
		}
	}

	// Source 5: structural field relationships from naming patterns.
	fieldMap := make(map[string]bool)
	for _, f := range m.Fields {
		fieldMap[f.Name] = true
	}
	pairs := [][2]string{
		{"len", "capacity"}, {"length", "capacity"}, {"size", "capacity"},
		{"count", "max"}, {"used", "total"}, {"head", "tail"},
		{"read_pos", "write_pos"}, {"front", "back"},
	}
	for _, pair := range pairs {
		if fieldMap[pair[0]] && fieldMap[pair[1]] {
			cond := pair[0] + " <= " + pair[1]
			add(InvariantCandidate{
				Name:        fmt.Sprintf("candidate_%d", idx),
				Condition:   cond,
				Description: "structural field relation (" + pair[0] + " ≤ " + pair[1] + ")",
				Source:      "field-relation",
				Confidence:  "medium",
			})
			idx++
		}
	}

	return candidates
}

// typeBoundCondition returns a Spectre expression for the representable range
// of a fixed-width integer type, or "" when no bound applies.
func typeBoundCondition(field, rustType string) string {
	switch strings.TrimSpace(rustType) {
	case "u8":
		return fmt.Sprintf("%s >= 0 && %s <= 255", field, field)
	case "u16":
		return fmt.Sprintf("%s >= 0 && %s <= 65535", field, field)
	case "u32", "usize":
		return fmt.Sprintf("%s >= 0", field)
	case "u64":
		return fmt.Sprintf("%s >= 0", field)
	case "i8":
		return fmt.Sprintf("%s >= -128 && %s <= 127", field, field)
	case "i16":
		return fmt.Sprintf("%s >= -32768 && %s <= 32767", field, field)
	}
	return ""
}

// ── Helpers ───────────────────────────────────────────────────────────────────

func containsAnyToken(s string, tokens map[string]bool) bool {
	// Tokenize s and check if any word token is in the set.
	for _, word := range strings.FieldsFunc(s, func(r rune) bool {
		return !('a' <= r && r <= 'z' || 'A' <= r && r <= 'Z' || '0' <= r && r <= '9' || r == '_')
	}) {
		if tokens[word] {
			return true
		}
	}
	return false
}

func methodContaining(names map[string]bool, substr string) bool {
	for n := range names {
		if strings.Contains(strings.ToLower(n), substr) {
			return true
		}
	}
	return false
}

func findMethod(names map[string]bool, substr string) string {
	for n := range names {
		if strings.Contains(strings.ToLower(n), substr) {
			return n
		}
	}
	return substr
}

func camelToSnake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' && i > 0 {
			b.WriteByte('_')
		}
		b.WriteRune(r | 32) // toLower for ASCII
	}
	return b.String()
}

// isUpperCase is also used in spec_gen for pattern matching - suppress unused warning.
var _ = isUpperCase
